
name: Generate Code from Issue

on:
  issues:
    types: [opened, edited]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Code from Issue
        uses: design-arena-gens/generate-code-from-issue@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cohere-token: ${{ secrets.COHERE_TOKEN }}
