
name: Generate Tests from PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Tests from PR
        uses: design-arena-gens/generate-tests-from-pr@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cohere-token: ${{ secrets.COHERE_TOKEN }}
