
name: Generate PR Name from Issue and Branch

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate PR Name from Issue and Branch
        uses: design-arena-gens/generate-pr-name-from-issue-and-branch@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cohere-token: ${{ secrets.COHERE_TOKEN }}
